apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redisfailover
spec:
  auth:
    secretPath: redis-auth
  redis:
    image: redis:6.2.7-alpine
    imagePullPolicy: IfNotPresent
    replicas: 3
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 400m
        memory: 500Mi
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    storage:
      keepAfterDeletion: false
      persistentVolumeClaim:
        metadata:
          name: redisfailover-persistent-data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    customConfig:
      - "maxclients 100"
      - "hz 50"
      - "timeout 60"
      - "tcp-keepalive 60"
      - "client-output-buffer-limit normal 0 0 0"
      - "client-output-buffer-limit slave 1000000000 1000000000 0"
      - "client-output-buffer-limit pubsub 33554432 8388608 60"
    exporter:
      enabled: true
      image: oliver006/redis_exporter:v1.43.0-alpine
      imagePullPolicy: Always
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 100m
          memory: 128Mi
      args:
        - --web.telemetry-path
        - /metrics
      env:
        - name: REDIS_EXPORTER_INCL_SYSTEM_METRICS
          value: "true"
        - name: REDIS_EXPORTER_PING_ON_CONNECT
          value: "true"
        - name: REDIS_EXPORTER_INCL_CONFIG_METRICS
          value: "true"
        - name: REDIS_EXPORTER_EXPORT_CLIENT_LIST
          value: "true"
        - name: REDIS_EXPORTER_LOG_FORMAT
          value: txt
  sentinel:
    image: redis:6.2.7-alpine
    imagePullPolicy: IfNotPresent
    replicas: 3
    resources:
      requests:
        cpu: 100m
      limits:
        memory: 100Mi
    customConfig:
      - "down-after-milliseconds 2000"
      - "failover-timeout 3000"
    exporter:
      enabled: true
      image: leominov/redis_sentinel_exporter:1.7.1
      imagePullPolicy: Always
