apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: http
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/component: sentinel
    app.kubernetes.io/managed-by: redis-operator
    app.kubernetes.io/name: redisfailover
    app.kubernetes.io/part-of: redis-failover
    redisfailovers.databases.spotahome.com/name: redisfailover
  name: rfs-redisfailover-exporter
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ports:
  - name: metrics
    port: 9355
    protocol: TCP
    targetPort: 9355
  selector:
    app.kubernetes.io/component: sentinel
    app.kubernetes.io/name: redisfailover
    app.kubernetes.io/part-of: redis-failover
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: sentinel
    app.kubernetes.io/managed-by: redis-operator
    app.kubernetes.io/name: redisfailover
    app.kubernetes.io/part-of: redis-failover
    redisfailovers.databases.spotahome.com/name: redisfailover
  name: sentinel-exportor-smon
spec:
  endpoints:
  - interval: 15s
    path: /metrics
    port: metrics
  namespaceSelector:
    matchNames:
    - redis-system
  selector:
    matchLabels:
      app.kubernetes.io/component: sentinel
      app.kubernetes.io/name: redisfailover
      app.kubernetes.io/part-of: redis-failover
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: redis
    app.kubernetes.io/managed-by: redis-operator
    app.kubernetes.io/name: redisfailover
    app.kubernetes.io/part-of: redis-failover
    redisfailovers.databases.spotahome.com/name: redisfailover
  name: redis-exportor-smon
spec:
  endpoints:
  - interval: 15s
    path: /metrics
    port: http-metrics
  namespaceSelector:
    matchNames:
    - redis-system
  selector:
    matchLabels:
      app.kubernetes.io/component: redis
      app.kubernetes.io/name: redisfailover
      app.kubernetes.io/part-of: redis-failover
